const data = {
  products: [
    {
      _id: '1',
      name: 'Nothing Ear 2',
      slug: 'nothing-ear-2',
      image: '/images/Nothing-ear-2.jpg',
      categories: 'earbuds',
      price: '11,999',
      brand: 'Nothing',
      rating: 4.7,
      reviews: 92,
      countInStock: 50,
      description: 'High-quality earbuds with ANC and crystal-clear sound.'
    },
    {
      _id: '2',
      name: 'boAt Airdopes 141',
      slug: 'boat-airdopes-141',
      image: '/images/boat-airdopes-141.jpg',
      categories: 'earbuds',
      price: '1,299',
      brand: 'boAt',
      rating: 4.3,
      reviews: 3400,
      countInStock: 75,
      description: 'Affordable true wireless earbuds with long battery life.'
    },
    {
      _id: '3',
      name: 'Sony WF-1000XM5',
      slug: 'sony-wf-1000xm5',
      image: '/images/sony-wf-1000xm5.jpg',
      categories: 'earbuds',
      price: '24,990',
      brand: 'Sony',
      rating: 4.8,
      reviews: 1120,
      countInStock: 45,
      description: 'Top-tier ANC earbuds with immersive audio experience.'
    },
    {
      _id: '4',
      name: 'Redragon K617 Fizz',
      slug: 'redragon-k617-fizz',
      image: '/images/redragon-k617.jpg',
      categories: 'keyboard',
      price: '2,200',
      brand: 'Redragon',
      rating: 4.5,
      reviews: 870,
      countInStock: 60,
      description: 'Compact mechanical keyboard with vibrant RGB lighting.'
    },
    {
      _id: '5',
      name: 'Logitech MX Master 3S',
      slug: 'logitech-mx-master-3s',
      image: '/images/logitech-mx-master-3s.jpg',
      categories: 'mouse',
      price: '9,900',
      brand: 'Logitech',
      rating: 4.9,
      reviews: 2140,
      countInStock: 35,
      description: 'Premium wireless mouse for professionals and creatives.'
    },
    {
      _id: '6',
      name: 'LG UltraGear 24" 144Hz',
      slug: 'lg-ultragear-24-144hz',
      image: '/images/lg-ultragear-24.jpg',
      categories: 'monitor',
      price: '11,999',
      brand: 'LG',
      rating: 4.6,
      reviews: 765,
      countInStock: 40,
      description: 'Smooth gaming monitor with high refresh rate and vibrant colors.'
    },
    {
      _id: '7',
      name: 'Samsung Galaxy Watch 6',
      slug: 'samsung-galaxy-watch-6',
      image: '/images/galaxy-watch-6.jpg',
      categories: 'smartwatch',
      price: '26,999',
      brand: 'Samsung',
      rating: 4.7,
      reviews: 980,
      countInStock: 38,
      description: 'Stylish smartwatch with advanced health tracking features.'
    },
    {
      _id: '8',
      name: 'Noise ColorFit Icon 3',
      slug: 'noise-colorfit-icon-3',
      image: '/images/noise-icon-3.jpg',
      categories: 'smartwatch',
      price: '1,499',
      brand: 'Noise',
      rating: 4.1,
      reviews: 1300,
      countInStock: 70,
      description: 'Budget-friendly smartwatch with essential fitness tracking.'
    },
    {
      _id: '9',
      name: 'Mi Power Bank 3i 20000mAh',
      slug: 'mi-power-bank-3i-20000mah',
      image: '/images/mi-powerbank-4i.jpg',
      categories: 'powerbank',
      price: '1,799',
      brand: 'Mi',
      rating: 4.4,
      reviews: 4100,
      countInStock: 95,
      description: 'Reliable high-capacity power bank with dual USB output.'
    },
    {
      _id: '10',
      name: 'GoPro Hero 12',
      slug: 'gopro-hero-12',
      image: '/images/gopro-hero-12.jpg',
      categories: 'camera',
      price: '45,000',
      brand: 'GoPro',
      rating: 4.9,
      reviews: 520,
      countInStock: 32,
      description: 'High-end action camera for professional video capture.'
    },
    // Continue with the remaining products 11–25 similarly...
        {
      _id: '11',
      name: 'Razer Huntsman Mini',
      slug: 'razer-huntsman-mini',
      image: '/images/razer-huntsman-mini.jpg',
      categories: 'keyboard',
      price: '10,500',
      brand: 'Razer',
      rating: 4.6,
      reviews: 1900,
      countInStock: 40,
      description: 'Compact 60% mechanical keyboard with Razer Optical Switches.'
    },
    {
      _id: '12',
      name: 'Apple AirPods Pro 2',
      slug: 'apple-airpods-pro-2',
      image: '/images/airpods-pro-2.jpg',
      categories: 'earbuds',
      price: '24,900',
      brand: 'Apple',
      rating: 4.8,
      reviews: 4200,
      countInStock: 65,
      description: 'Premium earbuds with adaptive ANC and spatial audio.'
    },
    {
      _id: '13',
      name: 'Anker Nano II 65W',
      slug: 'anker-nano-ii-65w',
      image: '/images/anker-nano-ii.jpg',
      categories: 'charger',
      price: '4,500',
      brand: 'Anker',
      rating: 4.6,
      reviews: 460,
      countInStock: 90,
      description: 'Fast charger with GaN technology and universal compatibility.'
    },
    {
      _id: '14',
      name: 'Zebronics Keyboard',
      slug: 'zebronics-transformer-keyboard',
      image: '/images/zebronics-transformer.jpg',
      categories: 'keyboard',
      price: '1,199',
      brand: 'Zebronics',
      rating: 4.2,
      reviews: 1200,
      countInStock: 55,
      description: 'Stylish wired gaming keyboard with multicolor LED backlight.'
    },
    {
      _id: '15',
      name: 'Realme Buds T300',
      slug: 'realme-buds-t300',
      image: '/images/realme-buds-t300.jpg',
      categories: 'earbuds',
      price: '2,299',
      brand: 'Realme',
      rating: 4.3,
      reviews: 1900,
      countInStock: 78,
      description: 'True wireless earbuds with deep bass and ENC calling.'
    },
    {
      _id: '16',
      name: 'Samsung M5 Smart Monitor',
      slug: 'samsung-m5-smart-monitor',
      image: '/images/samsung-m5-monitor.jpg',
      categories: 'monitor',
      price: '18,999',
      brand: 'Samsung',
      rating: 4.5,
      reviews: 710,
      countInStock: 30,
      description: 'Smart monitor with built-in apps, Wi-Fi, and FHD display.'
    },
    {
      _id: '17',
      name: 'DJI Osmo Mobile 6',
      slug: 'dji-osmo-mobile-6',
      image: '/images/dji-osmo-6.jpg',
      categories: 'gimbal',
      price: '13,000',
      brand: 'DJI',
      rating: 4.7,
      reviews: 850,
      countInStock: 42,
      description: 'Handheld smartphone gimbal for smooth cinematic video.'
    },
    {
      _id: '18',
      name: 'Logitech C920 Webcam',
      slug: 'logitech-c920-webcam',
      image: '/images/logitech-c920.jpg',
      categories: 'camera',
      price: '6,500',
      brand: 'Logitech',
      rating: 4.4,
      reviews: 1500,
      countInStock: 58,
      description: 'HD webcam with stereo audio and auto light correction.'
    },
    {
      _id: '19',
      name: 'Apple Watch SE',
      slug: 'apple-watch-se',
      image: '/images/apple-watch-se.jpg',
      categories: 'smartwatch',
      price: '29,900',
      brand: 'Apple',
      rating: 4.6,
      reviews: 2100,
      countInStock: 35,
      description: 'Affordable Apple smartwatch with essential health features.'
    },
    {
      _id: '20',
      name: 'boAt Xtend Plus',
      slug: 'boat-xtend-plus',
      image: '/images/boat-xtend-plus.jpg',
      categories: 'smartwatch',
      price: '2,999',
      brand: 'boAt',
      rating: 4.4,
      reviews: 1400,
      countInStock: 63,
      description: 'Feature-rich smartwatch with AMOLED display and BT calling.'
    },
    {
      _id: '21',
      name: 'Logitech MX Mechanical',
      slug: 'logitech-mx-mechanical',
      image: '/images/logitech-mx-mechanical.jpg',
      categories: 'keyboard',
      price: '13,500',
      brand: 'Logitech',
      rating: 4.9,
      reviews: 1350,
      countInStock: 50,
      description: 'Premium mechanical keyboard with low-profile tactile keys.'
    },
    {
      _id: '22',
      name: 'boAt Dual Port Car Charger',
      slug: 'boat-dual-port-car-charger',
      image: '/images/boat-car-charger.jpg',
      categories: 'charger',
      price: '699',
      brand: 'boAt',
      rating: 4.3,
      reviews: 890,
      countInStock: 100,
      description: 'Compact dual-port charger for fast charging on the go.'
    },
    {
      _id: '23',
      name: 'Sony Alpha ZV-E10 Camera',
      slug: 'sony-alpha-zv-e10-camera',
      image: '/images/sony-zv-e10.jpg',
      categories: 'camera',
      price: '58,000',
      brand: 'Sony',
      rating: 4.8,
      reviews: 490,
      countInStock: 20,
      description: 'Mirrorless camera perfect for vlogging and content creators.'
    },
    {
      _id: '24',
      name: 'HyperX Pulsefire Mouse',
      slug: 'hyperx-pulsefire-haste-mouse',
      image: '/images/hyperx-haste.jpg',
      categories: 'mouse',
      price: '3,299',
      brand: 'HyperX',
      rating: 4.5,
      reviews: 950,
      countInStock: 68,
      description: 'Ultra-light gaming mouse with customizable DPI and RGB.'
    },
    {
      _id: '25',
      name: 'Amazfit GTS 4 Smartwatch',
      slug: 'amazfit-gts-4-smartwatch',
      image: '/images/amazfit-gts-4.jpg',
      categories: 'smartwatch',
      price: '16,999',
      brand: 'Amazfit',
      rating: 4.6,
      reviews: 860,
      countInStock: 47,
      description: 'Elegant smartwatch with GPS, AMOLED display, and Alexa built-in.'
    }

  ]
};

export default data;
